In [1]:
import numpy as np

## (1) 將下兩列array存成npz檔

array1 = np.array(range(30)) <br>
array2 = np.array([2,3,5])


In [2]:
array1 = np.array(range(30)) 
array2 = np.array([2,3,5])
np.savez('result.npz', a= array1, b = array2)

In [3]:
file = np.load('result.npz')
print(file['a'])
print(file['b'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


## (2) 讀取剛剛的npz檔，加入下列 array 一起存成新的npz檔

In [4]:
array3 = np.array([3,4,5])

In [5]:
np.savez('new.npz', a = file['a'], b = file['b'], c = array3)
new_file = np.load('new.npz')
print(new_file['a'])
print(new_file['b'])
print(new_file['c'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[3 4 5]
