## 載入套件

In [1]:
import numpy as np

## (1) 陣列重塑
#### 將下列陣列 (array1)，轉成維度為 (5X6) 的array，順序按列填充。( hint:order="F" )

In [3]:
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
array1.reshape((6,5), order='F')

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## (2) 找出符合條件的元素
##### 呈上題的 array，找出被 6 除餘 1 的數的索引

In [7]:
np.where(array1%6==1)

(array([ 1,  7, 13, 19, 25]),)