## 載入套件

In [1]:
import numpy as np

## (1) 陣列重塑
#### 將下列陣列 (array1)，轉成維度為 (5X6) 的array，順序按列填充。( hint:order="F" )

In [3]:
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
new_array = array1.reshape(5,6, order='F')
new_array

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

## (2) 找出符合條件的元素
##### 呈上題的 array，找出被 6 除餘 1 的數的索引

In [12]:
np.where(new_array%6==1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))