## 載入套件

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

## (1) 建立 Numpy 等差數列
#### 首數為 0，尾數為 20，公差為 1

In [3]:
A = np.arange(0,21,1)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## (2) 從 A 數列取出偶數
#### 透過索引值進行切片 (slicing) 找到偶數值

In [4]:
A[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## (3) 從 A 數列取出 3 的倍數

In [5]:
A[A%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])